### ISSUE TITLE
[Feat] Save Task List Locally Using Shared Preferences

### ISSUE THREAD

**Issue by pranavkonidena** [IMGIITRoorkee/Taskly#12]
**Is your feature request related to a problem? Please describe.**
Currently, when the app is closed or the device is restarted, the task list is lost. Users may find it frustrating to lose their task data every time they exit the app or the app crashes. Implementing local storage will allow users to persist their task list between sessions and improve the overall user experience.

**Describe the solution you'd like**
Save the task list locally using SharedPreferences so that users’ tasks are stored even after the app is closed or the device is restarted.
Each task’s details (e.g., title, description, due date, priority) should be stored locally and retrieved when the app is reopened.
Ensure that the app retrieves and loads the stored task list on startup, allowing users to continue from where they left off.

**Comment by sommye-ctr** [comment]
Wouldn't a local db like sqlite be better for this? For storing in shared preferences, we would need to convert the object to json to store it as string and then decode it back

**Comment by pranavkonidena** [comment]
@sommye-ctr you are right but here we want you to explicitly use Shared Prefs as profile data in android is generally stored in Shared Preferences, room DB is an option but has some initial setup which is why we asked Shared Preferences

**Comment by pranavkonidena** [comment]
Also, please mention either me or @Akshit517 in any issue thread while commenting, like this we may not respond promptly
