### ISSUE TITLE
[Bug] Add task not working

### ISSUE THREAD

**Issue by pranavkonidena** [IMGIITRoorkee/Taskly#16]
**Describe the bug**
The "Add Task" functionality is not working as expected. When the user attempts to add a task, either nothing happens or an error message is displayed. This prevents users from creating new tasks in the app.
To Reproduce

**Steps to reproduce the behavior**:

    Open the app.
    Click on the "Add Task Floating" button.
    Fill in the task details (e.g., title, due date).
    Click on the "Save" button to add the task.
    See error: The task is not added, and no confirmation or success message is shown.

**Expected behavior**

The task should be added to the list, and the user should see a success message or be redirected to the task list page with the newly created task visible. If there is an issue, an appropriate error message should be displayed.
Screenshots

**Smartphone**

    Device: Iphone 13 Pro Max
    OS: iOS 16.1

**Additional context**
This issue may be related to a problem with saving the task data or issues with the button functionality. It might also be caused by incorrect API calls or a failure in the task saving logic.

**Comment by sommye-ctr** [comment]
How should the task list screen be managed from Home Screen, what should be shown on Home Screen to navigate to the list screen?
