### ISSUE TITLE
[Feat] Splash Screen

### ISSUE THREAD

**Issue by pranavkonidena** [IMGIITRoorkee/Taskly#2]
**Is your feature request related to a problem? Please describe.**
Currently, the app lacks a welcoming entry point, which makes the transition from launching the app to interacting with it feel abrupt. A splash screen can enhance user experience by giving a polished look and making the app feel more professional.

**Describe the solution you'd like**
A splash screen that displays the Taskly logo and tagline ("Your Personal Task Manager") for a few seconds when the app is launched.
Smooth animations such as a fade-in effect for the logo and tagline.

**Additional context**
Duration: The splash screen should last no more than 3 seconds and transition seamlessly into the main app.

**Comment by sommye-ctr** [comment]
Can one use this [flutter_native_splash](https://pub.dev/packages/flutter_native_splash) - it is a commonly used package

**Comment by pranavkonidena** [comment]
@sommye-ctr I would advise against using the package. Please do a custom implementation
