### ISSUE TITLE
[Bug]Editing task loses its deadline

### ISSUE THREAD

**Issue by sommye-ctr** [IMGIITRoorkee/Taskly#77]
**Describe the bug**
Whenever a user edits a task (which already has a deadline) and he does not change the deadline - the original deadline is lost.

**To Reproduce**
1. Go to 'TaskFormScreen' and add a task
2. Click on edit option of the created task in HomeScreen
3. Click on save

**Expected behavior**
The original deadline should remain the same, if the user has not selected any new deadline.

**Comment by Sanat-Jha** [comment]
Tried to reproduce this bug but didn't found anything like this, the deadline is perfectly saved and not lost. Please share more details of what kind of bug are you facing. 
I tried editing the task many times in all kind of ways and didn't face any data loss.
